#! /bin/sh

#AUTOSTART
sxhkd -c ~/.config/sxhkdrc &
xfce4-power-manager &
picom --experimental-backend &
rofi &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width        0
bspc config window_gap          5

bspc config top_padding         0
bspc config left_padding        30

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
